# root_dir: "/home/ubnps23/tecHub/SLS_dev/sls-models/femtest/structures/bev_trunc_octahedrons"
root_dir: "__AUTO__"

# stl_filename: "layer_gen_10x10x1_a65.0_b65.0_c48.75_alpha35.0.stl"
stl_filename: "RUN_layer_BTOCTS_10x10x1_a65.0_b65.0_c48.75_alpha35.stl"
# stl_filename: "EXTRA_RUN_BT8_alpha37_20x20x1_a65.0_b65.0_c48.75.stl"
doc_prefix: "Steel_bev_trunc_octahedrons_"

faces_num: 44
gui: False
tolerance: 0.1

constraints:
  fixed_faces_file: "fixed_faces.txt"
  under_pressure_file: "under_pressure.txt"
  # prefix: "Edge"
  TOUCH_UNIT_NAME_PREFIX: "Face"
  border_tolerance: 0.8 # 0.8
  apply_tolerance: 0.25 # 0.25

contacts:
  activate_friction: False
  cc_pairs_file: "cc_pairs.csv"
  centers_dist_for_contact: 50.0   # mm
  friction_coeff: 0.3
  slope_coeff: 1.0