root_dir: "/home/ubnps23/tecHub/SLS_dev/sls-models/femtest/structures/tetrahedrons_plate"
stl_filename: "tetrah_sls.stl"
doc_prefix: "Steel_tetrahedrons_"

faces_num: 4
gui: False
faces_num: 4
tolerance: 0.1

constraints:
  fixed_faces_file: "fixed_faces.txt"
  under_pressure_file: "under_pressure.txt"
  TOUCH_UNIT_NAME_PREFIX: "Edge"

contacts:
  activate_friction: false
  cc_pairs_file: "cc_pairs.csv"
  centers_dist_for_contact: 50.0   # mm
  friction_coeff: 0.3
  slope_coeff: 1.0